---
- name: Install epel
  when: ansible_os_family == "RedHat"
  yum:
    name: epel-release
    state: latest

- name: Adding Kubernetes repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no
  register: kuberepo
